import type { GetStaticProps } from 'next'
import Head from 'next/head'
import { type } from 'os'
import About from './About'
import ContactMe from './ContactMe'
import Header from './Header'
import Hero from './Hero'
import ProjectExperience from './ProjectExperience'
import Projects from './Projects'
import Skills from './Skills'
import { Experience, PageInfo, Project, Skill, Social } from '../typings'
import { fetchExperiences } from '../utils/fetchExperiences'
import { fetchPageInfos } from '../utils/fetchPageInfos'
import { fetchProjects } from '../utils/fetchProjects'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchSocials } from '../utils/fetchSocials'

type Props = {
  pageInfo: PageInfo;
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];

}

const Home = ({pageInfo,skills,projects,experiences,socials}:Props) => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80  ' >

      {/* Head: here goes all the metaData of the app, the title fav icon and meta*/}
      <Head>
        <title >Francisco Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/*Header*/}
      <Header socials={socials} />
      {/*Hero*/}
      <section id='hero' className='snap-center'>
        <Hero pageInfo={pageInfo} />
      </section>
      {/*About*/}
      <section id='about' className='snap-center'>

        <About pageInfo={pageInfo} />


      </section>
      {/*Experiencie*/}
      <section id='experience' className='snap-center'>
        <ProjectExperience experiences={experiences} />
      </section>
      {/*Skills*/}
      <section id='skills' className='snap-start'>
        <Skills skills={skills} />
      </section>
      {/*Projects*/}
      <section id='projects' className='snap-start'>
        <Projects projects={projects} />
      </section>
      {/*COntactme*/}
      <section id='contact' className='snap-start'>
        <ContactMe />
      </section>


    </div>
  )
}

export default Home



export const getStaticProps : GetStaticProps<Props> = async () => {

  const skills: Skill[] = await fetchSkills();
  const pageInfo: PageInfo = await fetchPageInfos();
  const experiences: Experience[] = await fetchExperiences();
  const projects: Project[] = await fetchProjects();
  const socials: Social[] = await fetchSocials();
 
  return {
    props :{
      pageInfo, skills, experiences, projects, socials
    },
    revalidate:2,
  }

}




