import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'



const Home: NextPage = () => {
  return (
    <div >
      {/* Head: here goes all the metaData of the app, the title fav icon and meta*/}
      <Head>
        <title >Francisco Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 >Creating Amazing Portafolio</h1>
      {/*Header*/}
      <Header/>
      {/*Hero*/}
      {/*About*/}
      {/*Experiencie*/}
      {/*Skills*/}
      {/*Projects*/}
      {/*COntactme*/}


    </div>
  )
}

export default Home
