import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Header from '../components/Header'
import Hero from '../components/Hero'
import ProjectExperience from '../components/ProjectExperience'
import Skills from '../components/Skills'



const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0  ' >

      {/* Head: here goes all the metaData of the app, the title fav icon and meta*/}
      <Head>
        <title >Francisco Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      {/*Header*/}
      <Header />
      {/*Hero*/}
      <section id='hero' className='snap-center'> 
<Hero/>
      </section>
      {/*About*/}
      <section id='about' className='snap-center'>

        <About/>


      </section>
      {/*Experiencie*/}
      <section id='experience' className='snap-center'>
        <ProjectExperience/>
      </section>
      {/*Skills*/}
      <section id='skills' className='snap-center'>
        <Skills/>
      </section>
      {/*Projects*/}
      {/*COntactme*/}


    </div>
  )
}

export default Home
