import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import ContactMe from '../components/ContactMe'
import Header from '../components/Header'
import Hero from '../components/Hero'
import ProjectExperience from '../components/ProjectExperience'
import Projects from '../components/Projects'
import Skills from '../components/Skills'



const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80  ' >

      {/* Head: here goes all the metaData of the app, the title fav icon and meta*/}
      <Head>
        <title >Francisco Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/*Header*/}
      <Header />
      {/*Hero*/}
      <section id='hero' className='snap-center'>
        <Hero />
      </section>
      {/*About*/}
      <section id='about' className='snap-center'>

        <About />


      </section>
      {/*Experiencie*/}
      <section id='experience' className='snap-center'>
        <ProjectExperience />
      </section>
      {/*Skills*/}
      <section id='skills' className='snap-start'>
        <Skills />
      </section>
      {/*Projects*/}
      <section id='projects' className='snap-start'>
        <Projects />
      </section>
      {/*COntactme*/}
      <section id='contact' className='snap-start'>
        <ContactMe />
      </section>


    </div>
  )
}

export default Home
